### PR TITLE
Apply Tim's change to show stock adjustments and internal stock requests 

### PR DESCRIPTION
**Pull request by TurboPT**
Change applied based on forum: http://www.weberp.org/forum/showthread.php?tid=8111

### CODE REVIEW

**Comment by andrewcouling** [comment]
Why does this commit reference my petty cash pull request? I'm confused.

**Comment by TurboPT** [comment]
Me too on the confusion, as I've seen similar with other pulls, but it only
showed the one file changed by Tim.

**Comment by andrewcouling** [comment]
I noticed that your repo is a forked of timschofield/webERP-svn, rather than a fork of webERP-team/webERP.
Could this be the cause? Perhaps it doesn't matter either way.

image

**Comment by TurboPT** [comment]
When I tried to fork the webERP team, github kept redirecting to my
already-existing fork from Tim.

I guess trying to create a fork-of-a-fork is not allowed?  I was already
forked from Tim before the webERP-team was created.


Thanks!,
-Paul
============
*https://www.linkedin.com/in/paul-thursby
<https://www.linkedin.com/in/paul-thursby>*

**Comment by andrewcouling** [comment]
I've had no problems, and mine is a fork of a fork.
It's perhaps worth trying again

**Comment by TurboPT** [comment]
I tried again, but this is the behavior:

1. I set the page to webERP-team/webERP
2. Then click the 'Fork' button in the upper-right corner
3. I get redirected to my own webERP-svn repository

Is there some other step necessary?

**Comment by andrewcouling** [comment]
I don't think your missing a step. The process appears to be the same that I followed.
Maybe there's a problem with the child/parent relationship which the process, in your case, is trying to create.
I can't find any info to suggest that deleting your repo will affect anything you've pushed to webERP-team (history etc).

**Pull request merged**
