### PR TITLE
Change log updated and formatted in tabular markdown

### PR DESCRIPTION
**Pull request by andrewcouling**

### CODE REVIEW

**Comment by TurboPT** [comment]
@andrewcouling 
Looks like Phil already merged, but was curious if the changelog.md is automatically updated with other commits somehow, or what needs to be done for updates?

Appears to have a nice format, from what I can tell based on the diff.

**Comment by andrewcouling** [comment]
Hi Paul,
Unfortunately no, it isn't automatically updated.
I would recommend that, from this point onwards, we should revert to the practice of updating CHANGELOG.md with every commit.
I have a git log command, which outputs logs in tabular markdown format. It may be helpful if at some point we need to update the changelog retrospectively.
I will add some notes on this to the GH Wiki.

**Comment by ExsonQu2018** [comment]
Hi, 
If we have to update it manually, why not use our doc/change file? 
Exson

**Comment by andrewcouling** [comment]
Hi Exson,

The intention was for doc/CHANGELOG.md to replace doc/change.log.
They are essentially the same, but with tabular formatting in markdown, which renders when viewed within the GH interface.

Andy.

**Comment by andrewcouling** [comment]
There are some projects which boast of the ability to automate changelog generation, but they relie on the use of GH issues and labelling.

**Pull request merged**
