### PR TITLE
replaced curly braces in PHPExcel for PHP 8 compat

### PR DESCRIPTION
**Pull request by dalers**
Replaced curly braces in PHPExcel with square brackets. PHPExcel now passes PHP 8 lint (php -l). Has not been tested.

### CODE REVIEW

**Comment by dalers** [comment]
Hi @PhilDaintree, it's good to see you're still around! :-)  Fyi my pull requests related to PHP 8 were a work in process, NOT tested, and I strongly suspect will cause you more trouble than assistance on the path to PHP 8 compatability. At the time, I did not fully understood all the issues related to PHP 8 and eventually hit a roadblock I did not have the coding skills or time to resolve. I requested in the webERP forum that the pull requests be reverted, but there was no response from TurboPT/PaulT. I would send you a link to my comments, but it appears the weberp.org domain has been abandoned and the forum is no longer :-(

I'll watch your repo for progress and can help testing if you make more progress than I did on PHP 8 compatibiity (or preferably 8.2 now, since 8.1 will be unsupported in November).

Cheers,
Dale

**Comment by PhilDaintree** [comment]
Hi DaleI am no developing webERP any more ... I did apply some pull requests from Tim a few days back but it has been a while since I got my hands dirty.PhilOn 26 Jun 2024 05:25, Dale Scott ***@***.***> wrote:
Hi @PhilDaintree, it's good to see you're still around! :-)  Fyi my pull requests related to PHP 8 were a work in process, NOT tested, and I strongly suspect will cause you more trouble than assistance on the path to PHP 8 compatability. At the time, I did not fully understood all the issues related to PHP 8 and eventually hit a roadblock I did not have the coding skills or time to resolve. I requested in the webERP forum that the pull requests be reverted, but there was no response from TurboPT/PaulT. I would send you a link to my comments, but it appears the weberp.org domain has been abandoned and the forum is no longer :-(
I'll watch your repo for progress and can help testing if you make more progress than I did on PHP 8 compatibiity (or preferably 8.2 now, since 8.1 will be unsupported in November).
Cheers,
Dale

**Comment by dalers** [comment]
In that case, I would suggest you revert my commits (or from the last commit before my mucking about), and then merge any commits you want from Tim. Hope all is well in your world. Cheers.

**Comment by timschofield** [comment]
Dale, perhaps it would be best if you made the reverts on your repository and then just send a pull request to Phil?

That said, we need to be PHP8 compliant, so I would be happy to help you iron out any issues?

Thanks
Tim

**Comment by dalers** [comment]
Hi @timschofield, to "revert", I would probably just drop my personal webERP repo and re-clone the webERP-team/webERP repo at the last commit before my first "PHP8" commit (i.e. clone from TurbuPT's commit 124ebe3). I'm certain my git-fu is not up to yours, but I think this might also also be the simplest approach for @PhilDaintree. I.e. clone from last good commit, then merge your "New design for the login screen incorporating logos in (#228)" commit (dd4635a) followed by TubtoPT's "Use Html5 date (#211)" commit (7edd740). 

As for the project repo (webERP-team/webERP), I don't know how the master branch is useable as-is with my merged commits. If it was my project, I would consider re-constructing the project repo entirely and keep only the master branch with known good code for PHP 7.4, drop the old unused branches to simplify and eliminate confusion, and then create a new PHP8 stabilization branch from master with my PHP8 commits as a starting point. Also, what is the state of your QwaMoja project? (did I spell it correctly?) Perhaps it presents the best path forward?

Unfortunately, I don't recall exactly what roadblock I ran into, just that it was beyond my skills and likely needed someone with intimate familiarity the the existing code structure to see it through. Do you know if the forum contents are still available? If there's a backup of the forum, it could be worth restoring it off-line just to get my comments.

I can help with testing (and also repo management), but imho my skills would make me a very unsuitable choice for lead (if it was my project, I would certainly not want to see me as lead! ;-) ). Also I am not actively supporting any webERP systems (or at least I have not heard from the one client I did have for almost a year now, and his server has been offline for several months).

Also continuing the discussion here may not be the most convenient, or visible. Perhaps we should continue in the repo wiki, create a PHP8 issue, or even a email thread (my email is dale@dalescott.net) with other "core" developers.

Cheers,
Dale

**Pull request merged**
