### PR TITLE
fix purcahse order item to flag as completed 

### PR DESCRIPTION
**Pull request by expressachiever**
fix purchase order item to flag as completed when automatically receive purchase orders

### CODE REVIEW

**Comment by PhilDaintree** [comment]
Well, it is possible that the received  quantity is not actually
the total remaining balance on order - only when the whole
quantity has been received should the order be flagged as
completed. I don't think we should commit this change on
this basis

**Comment by expressachiever** [comment]
referring to the comments on lines 137-140

```
/* The code below automatically receives the outstanding balances on the purchase order ReceivePO and adds all the GRNs from that purchase order onto the invoice
 * This is geared towards smaller businesses that have purchase orders that are automatically approved by users, and they want to enter the invoice directly based
 * on the details entered in the purchase order screen.
 */
```

based on the workflow of the code, the status for purchorders is always set to 'Completed' at line 439-432

```
$sql="UPDATE purchorders
		SET status='Completed',
		stat_comment='" . $StatusComment . "'
		WHERE orderno='" . $_SESSION['PO'.$identifier]->OrderNo . "'";
```

there is no possible way for the user to enter the quantity received using this workflow to receive the items. hence, the completed flag should always be true in this case

**Comment by timschofield** [comment]
Although this fix is good (and should really be applied) it seems to me that this functionality as a whole is broken needs looking at.

Tim

**Comment by TurboPT** [comment]
I wasn't 100% certain based on Phil's comment, but I'll go ahead and pull.
(it is a minor change)

**Pull request merged**
